name: ${project.name}
version: ${project.version}
api-version: 1.16
main: $pluginMain

commands:
  peconomy:
    description: This is money command
    usage: /org.projecttl.plugin.peconomy <option> <target_player> <amount>
    aliases:
      - money